project_id = "pytqsqpjqgkfgktqihaa"

[functions.analytics-ai]
verify_jwt = true

[functions.analytics-chat]
verify_jwt = true

[functions.send-gsm-command]
verify_jwt = true

[functions.send-wifi-command]
verify_jwt = true
